{
 "title": "Avalanche Main Dashboard",
 "description": "Home dashboard with most important indicators for your node and machine",
 "tags": [ "Avalanche" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "CPU",
   "type": "gauge",
   "description": "Percentage of CPU used",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{job=~\"avalanchego-machine\", mode=\"idle\"}[1m])) by (instance)) * 100"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "gauge",
   "description": "Percentage of storage filled",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(((node_filesystem_size_bytes{job=~\"avalanchego-machine\", fstype=~\"ext4|vfat\"} - node_filesystem_free_bytes{job=~\"avalanchego-machine\", fstype=~\"ext4|vfat\"}) / node_filesystem_size_bytes{job=~\"avalanchego-machine\", fstype=~\"ext4|vfat\"}) * 100) by (instance)"
    }
   ]
  },
  {
   "title": "Failing health checks",
   "type": "gauge",
   "description": "Number of currently failing internal health checks",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avalanche_health_checks_failing{job=\"avalanchego\"}"
    }
   ]
  },
  {
   "title": "Staking Ratio",
   "type": "gauge",
   "description": "Ratio of Staked Avax / Total Supply of AVAX",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avalanche_P_vm_total_staked{job=\"avalanchego\"}/1000000000)/360000000",
     "legendFormat": "AVAX"
    }
   ]
  },
  {
   "title": "Peer count",
   "type": "graph",
   "description": "Number of peers node is connected to",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "expr": "avalanche_peers{job=\"avalanchego\"}",
     "legendFormat": "Peers"
    }
   ]
  },
  {
   "title": "Peer Delta over 5m",
   "type": "graph",
   "description": "Number of peers node is connected to",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "expr": "delta(avalanche_peers{job=\"avalanchego\"}[5m])",
     "legendFormat": "Peers"
    }
   ]
  },
  {
   "title": "Total staked",
   "type": "stat",
   "description": "Amount of AVAX currently staked",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avalanche_P_vm_total_staked{job=\"avalanchego\"}/1000000000",
     "legendFormat": "AVAX"
    }
   ]
  },
  {
   "title": "24H Staked Avax Change",
   "type": "stat",
   "description": "Amount of AVAX Stake difference over 24 hours",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avalanche_P_vm_total_staked{job=\"avalanchego\"} - avalanche_P_vm_total_staked{job=\"avalanchego\"} offset 1d)/1000000000",
     "legendFormat": "AVAX"
    }
   ]
  },
  {
   "title": "Stake connected",
   "type": "stat",
   "description": "Amount of network stake node is currently connected to",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avalanche_P_vm_percent_connected{job=\"avalanchego\"}"
    }
   ]
  },
  {
   "title": "Peer count",
   "type": "stat",
   "description": "Number of peers node is connected to",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avalanche_peers{job=\"avalanchego\"}",
     "legendFormat": "Peers"
    }
   ]
  },
  {
   "title": "Network Latency",
   "type": "stat",
   "description": "Average amount of time before a response arrives",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avalanche_avg_network_latency/1000000000"
    }
   ]
  },
  {
   "title": "C Chain Blocks",
   "type": "graph",
   "description": "Number of accepted and rejected blocks on the C chain in the last minute.",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(increase(avalanche_C_blks_accepted_count{job=\"avalanchego\"}[1m]))",
     "legendFormat": "Accepted"
    },
    {
     "expr": "round(increase(avalanche_C_blks_rejected_count{job=\"avalanchego\"}[1m]))",
     "legendFormat": "Rejected"
    }
   ]
  },
  {
   "title": "Accepted Blocks/Vertices",
   "type": "bargauge",
   "description": "Number of blocks/vertices accepted in the last minute",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(avalanche_X_vtx_accepted_count{job=\"avalanchego\"}[1m]))",
     "legendFormat": "X Chain"
    },
    {
     "expr": "round(increase(avalanche_P_blks_accepted_count{job=\"avalanchego\"}[1m]))",
     "legendFormat": "P Chain"
    },
    {
     "expr": "round(increase(avalanche_C_blks_accepted_count{job=\"avalanchego\"}[1m]))",
     "legendFormat": "C Chain"
    }
   ]
  },
  {
   "title": "Processing",
   "type": "bargauge",
   "description": "Number of blocks/vrtices currently being processed by the node",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avalanche_X_bs_accepted_vts{job=\"avalanchego\"}",
     "legendFormat": "X Chain"
    },
    {
     "expr": "avalanche_P_bs_accepted{job=\"avalanchego\"}",
     "legendFormat": "P Chain"
    },
    {
     "expr": "avalanche_C_bs_accepted{job=\"avalanchego\"}",
     "legendFormat": "C Chain"
    }
   ]
  },
  {
   "title": "Queries success",
   "type": "bargauge",
   "description": "Number of successful queries per chain in the last minute",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(increase(avalanche_X_handler_chits_count{job=\"avalanchego\"}[1m]) + 1) / (increase(avalanche_X_handler_chits_count{job=\"avalanchego\"}[1m]) + increase(avalanche_X_handler_query_failed_count{job=\"avalanchego\"}[1m]) + 1)",
     "legendFormat": "X Chain"
    },
    {
     "expr": "(increase(avalanche_P_handler_chits_count{job=\"avalanchego\"}[1m]) + 1) / (increase(avalanche_P_handler_chits_count{job=\"avalanchego\"}[1m]) + increase(avalanche_P_handler_query_failed_count{job=\"avalanchego\"}[1m]) + 1)",
     "legendFormat": "P Chain"
    },
    {
     "expr": "(increase(avalanche_C_handler_chits_count{job=\"avalanchego\"}[1m]) + 1) / (increase(avalanche_C_handler_chits_count{job=\"avalanchego\"}[1m]) + increase(avalanche_C_handler_query_failed_count{job=\"avalanchego\"}[1m]) + 1)",
     "legendFormat": "C Chain"
    }
   ]
  },
  {
   "title": "Benched nodes",
   "type": "bargauge",
   "description": "Number of peers currently being benched (ignored) by the node",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avalanche_X_benchlist_benched_num{job=\"avalanchego\"}",
     "legendFormat": "X Chain"
    },
    {
     "expr": "avalanche_P_benchlist_benched_num{job=\"avalanchego\"}",
     "legendFormat": "P Chain"
    },
    {
     "expr": "avalanche_C_benchlist_benched_num{job=\"avalanchego\"}",
     "legendFormat": "C Chain"
    }
   ]
  },
  {
   "title": "avax",
   "type": "stat",
   "description": "Price of avax vs eth",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prices{pair=\"avax_usd\"}",
     "legendFormat": "AVAX"
    }
   ]
  },
  {
   "title": "P Chain Blocks",
   "type": "graph",
   "description": "Number of accepted and rejected blocks on the P chain in the last minute.",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(increase(avalanche_P_blks_accepted_count{job=\"avalanchego\"}[1m]))",
     "legendFormat": "Accepted"
    },
    {
     "expr": "round(increase(avalanche_P_blks_rejected_count{job=\"avalanchego\"}[1m]))",
     "legendFormat": "Rejected"
    }
   ]
  },
  {
   "title": "Avax Supply",
   "type": "graph",
   "description": "Number of peers node is connected to",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "misc{value=\"supplyPostBurn\"}",
     "legendFormat": "Post Burn"
    },
    {
     "expr": "misc{value=\"AVAXsupply\"}",
     "legendFormat": "Max Supply"
    },
    {
     "expr": "misc{value=\"burnSupply\"}",
     "legendFormat": "C-Chain Burn"
    },
    {
     "expr": "misc{value=\"binanceAVAXsupply\"}",
     "legendFormat": "Binance Avax Supply"
    }
   ]
  },
  {
   "title": "Database Operations Latency",
   "type": "graph",
   "description": "Measures how long each database operation is taking on average",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "avalanche_db_put_latency_sum{job=\"avalanchego\"}/avalanche_db_put_latency_count{job=\"avalanchego\"}",
     "legendFormat": "put"
    },
    {
     "expr": "avalanche_db_get_latency_sum{job=\"avalanchego\"}/avalanche_db_get_latency_count{job=\"avalanchego\"}",
     "legendFormat": "get"
    },
    {
     "expr": "avalanche_db_delete_latency_sum{job=\"avalanchego\"}/avalanche_db_delete_latency_count{job=\"avalanchego\"}",
     "legendFormat": "delete"
    },
    {
     "expr": "avalanche_db_has_latency_sum{job=\"avalanchego\"}/avalanche_db_has_latency_count{job=\"avalanchego\"}",
     "legendFormat": "has"
    },
    {
     "expr": "avalanche_db_compact_size_sum{job=\"avalanchego\"}/avalanche_db_compact_size_count{job=\"avalanchego\"}",
     "legendFormat": "compact"
    },
    {
     "expr": "avalanche_db_batch_put_latency_sum{job=\"avalanchego\"}/avalanche_db_batch_put_latency_count{job=\"avalanchego\"}",
     "legendFormat": "batch put"
    },
    {
     "expr": "avalanche_db_batch_delete_latency_sum{job=\"avalanchego\"}/avalanche_db_batch_delete_latency_count{job=\"avalanchego\"}",
     "legendFormat": "batch delete"
    },
    {
     "expr": "avalanche_db_batch_reset_latency_sum{job=\"avalanchego\"}/avalanche_db_batch_reset_latency_count{job=\"avalanchego\"}",
     "legendFormat": "batch reset"
    },
    {
     "expr": "avalanche_db_batch_replay_latency_sum{job=\"avalanchego\"}/avalanche_db_batch_replay_latency_count{job=\"avalanchego\"}",
     "legendFormat": "batch replay"
    }
   ]
  },
  {
   "title": "X Chain Vertices",
   "type": "graph",
   "description": "Number of accepted and rejected vertices on the X chain in the last minute",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(increase(avalanche_X_vtx_accepted_count{job=\"avalanchego\"}[1m]))",
     "legendFormat": "Accepted"
    },
    {
     "expr": "round(increase(avalanche_X_vtx_rejected_count{job=\"avalanchego\"}[1m]))",
     "legendFormat": "Rejected"
    }
   ]
  },
  {
   "title": "Peer Versions",
   "type": "graph",
   "description": "Peer version of nodes connected",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Peer Count" }
   ],
   "targets": [
    {
     "expr": "peerstatus{status=\"up\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "ETH",
   "type": "stat",
   "description": "Price of ETH",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prices{pair=\"eth_usd\"}",
     "legendFormat": "ETH"
    }
   ]
  },
  {
   "title": "BTC",
   "type": "stat",
   "description": "Price of btc",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prices{pair=\"btc_usd\"}",
     "legendFormat": "BTC"
    }
   ]
  }
 ]
}