{
 "title": "Custom Feed",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "BTC/USD",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prices{pair=\"btc_usd\"}"
    }
   ]
  },
  {
   "title": "ETH/USD",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prices{pair=\"eth_usd\"}"
    }
   ]
  },
  {
   "title": "AVAX/USD",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prices{pair=\"avax_usd\"}"
    }
   ]
  },
  {
   "title": "Binance AVAX Supply",
   "type": "graph",
   "gridPos": { "h": 13, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "misc{value=\"binanceAVAXsupply\"}"
    }
   ]
  },
  {
   "title": "Upper Bound AVAX Supply",
   "type": "graph",
   "gridPos": { "h": 13, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "misc{value=\"AVAXsupply\"}"
    }
   ]
  },
  {
   "title": "AVAX Supply",
   "type": "graph",
   "gridPos": { "h": 21, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "misc{value=\"supplyPostBurn\"}"
    }
   ]
  },
  {
   "title": "AVAX/BTC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "yaxes": [
    { "format": "currencyBTC" }
   ],
   "targets": [
    {
     "expr": "prices{pair=\"avax_btc\"}"
    }
   ]
  },
  {
   "title": "AVAX/ETH",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "prices{pair=\"avax_eth\"}"
    }
   ]
  },
  {
   "title": "Peer Versions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Peer Count" }
   ],
   "targets": [
    {
     "expr": "peerstatus{status=\"up\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "C-Chain Block Number",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "misc{value=\"blockNumber\"}"
    }
   ]
  },
  {
   "title": "C-Chain Burn ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "misc{value=\"burnSupply\"}"
    }
   ]
  }
 ]
}